name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: Launchpad Extension
          path: ./target/LaunchpadX.bwextension